FROM amazoncorretto:21
LABEL maintainer="itsupport@gmail.com"
ADD target/bc-calculator-0.0.1-SNAPSHOT.jar bc-calculator-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","bc-calculator-0.0.1-SNAPSHOT.jar"]
EXPOSE 8081 